name: 发布构建与发布
env:
  GO_VERSION: 1.25.x
on:
  push:
    tags:
      - 'v*'
jobs:
  publishGitRelease:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: Unshallow repo
        run: git fetch --prune --unshallow

      - name: 设置go版本
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: 版本构建
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --verbose --clean --release-footer-tmpl=scripts/release/footer.md.tmpl --release-header-tmpl=scripts/release/head.md.tmpl
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}

